### ISSUE TITLE
Styling: Center content for readability 

### ISSUE THREAD

**Issue by tealleaf** [Zulu-Inuoe/git-go#4]
![image](https://user-images.githubusercontent.com/19731558/80778141-6018ff80-8b35-11ea-8e02-01e99b289d7d.png)

**Comment by tealleaf** [comment]
![image](https://user-images.githubusercontent.com/19731558/80778123-52fc1080-8b35-11ea-9283-dfcd92e162fe.png)

**Comment by Zulu-Inuoe** [comment]
Great, thanks!
